MainApp/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('kitchens/', views.nearbyKitchens, name='kitchens'),
    path('menu/<int:pk>/', views.Menu, name='menu'),
    path('add_to_favourite/<int:pk>/', views.add_to_favourite, name='add_to_favourite'),
    path('favouriteKitchens/', views.favouriteKitchens, name='favouriteKitchens'),
    path('cart/', views.Cart, name='cart'),
    path('login/', views.Login, name='login'),
    path('register/', views.Register, name='register'),
    path('updateProfile/', views.updateProfile, name='updateProfile'),
    path('logout/', views.Logout, name='logout'),
    path('test/', views.test, name='test'),
    # path('checkout/', views.Checkout, name='checkout'),
    path('orders/', views.orders, name='orders'),
    path('addReview/', views.addReview, name='addReview'),
    path('sendQueries/', views.sendQueries, name='sendQueries'),
    path('orderStatus/<int:pk>/', views.orderStatus, name='orderStatus'),
    path('contactUs/', views.contactUs, name='contactUs'),
    path('updates/', views.updates, name='updates'),
    path('firebase-messaging-sw.js', views.getServiceWorker, name='firebase-messaging-sw.js'),
    path('kitchen/', include('kitchen.urls')),
    path('userapi/', include('MainApp.api.urls')),
    path('kitapi/', include('kitchen.api.urls')),
]

dreamWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

kitchen/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('applogin', views.login, name='applogin'),
    path('apporderList', views.orderList, name='apporderList'),
    path('appchangeOrderStatus', views.changeOrderStatus, name='appchangeOrderStatus'),
    path('appupdatePayment', views.updatePayment, name='appupdatePayment'),
    path('apphandleNewOrder', views.handleNewOrder, name='apphandleNewOrder'),
    path('appgetOrder', views.getOrder, name='appgetOrder'),
    path('appupdateMessageToCustomer', views.updateMessageToCustomer, name='appupdateMessageToCustomer'),
    path('apphandleKitchenStatus', views.handleKitchenStatus, name='apphandleKitchenStatus'),
    path('apphandleMenu', views.handleMenu, name='apphandleMenu'),
    path('appaddMenuItems', views.addMenuItems, name='appaddMenuItems'),
    path('apphandleAllItems', views.handleAllItems, name='apphandleAllItems'),
    path('appaddNewItem', views.addNewItem, name='appaddNewItem'),
    path('appfetchItem', views.fetchItem, name='appfetchItem'),
]

kitchen/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.kitchenHomePage, name='kitchenHomePage'),
    path('kitRegister/', views.kitchenUserRegistration, name='kitchenRegistration'),
    path('updateKitUserProfile/', views.updateKitUserProfile, name='updateKitUserProfile'),
    path('kitLogin/', views.kitchenLogin, name='kitchenLogin'),
    path('createKitchen/', views.createKitchen, name='createKitchen'),
    path('updateKitchen/', views.updateKitchen, name='updateKitchen'),
    path('addFoodItems/', views.addFoodItems, name='addFoodItems'),
    path('handleStatus/', views.handleStatus, name='handleStatus'),
    path('orderList/', views.orderList, name='orderList'),
    path('orderHistory/', views.orderHistory, name='orderHistory'),
    path('subscription/', views.subscription, name='subscription'),
    path('paymentHistory/', views.paymentHistory, name='paymentHistory'),
    path('createCoupon/', views.createCoupon, name='createCoupon'),
    path('coupons/', views.coupons, name='coupons'),
    path('complaintsAndRefunds/', views.complaintsAndRefunds, name='complaintsAndRefunds'),
    path('handlePaytmResponse/', views.handlePaytmResponse, name='handlePaytmResponse'),
    # path('addSubItems/', views.addSubItems, name='addSubItems'),
]

kitchen/forms.py
from django import forms
from .models import Kitchens, Categories, Items, SubItems, Menus
from MainApp.models import User


class KitchenSignUpForm(forms.ModelForm):
	email = forms.CharField(widget=forms.EmailInput(
		attrs={'class': 'form-control', 'placeholder': 'Email'}))
	rpassword = forms.CharField(widget=forms.PasswordInput(
		attrs={'class': 'form-control', 'placeholder': 'Re-enter Password'}))
	password = forms.CharField(widget=forms.PasswordInput(render_value = True,
		attrs={'class': 'form-control', 'placeholder': 'Password'}))
	first_name = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'First Name'}))
	last_name = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Last Name'}))
	username = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Username'}))
	phone = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Phone No.', 'maxlength':'10', 'onkeypress':'return onlyNumberKey(event)'}))

	class Meta:
		model = User
		fields = ['username', 'email', 'phone', 'password',
					'rpassword', 'first_name', 'last_name']

		def save(self, commit=True):
			user = super().save(commit=False)
			user.is_kitchen = True
			if commit:
				user.save()
			return user

	def clean(self):
		cleaned_data = super(KitchenSignUpForm, self).clean()
		password = cleaned_data.get("password")
		rpassword = cleaned_data.get("rpassword")
		if password != rpassword:
			raise forms.ValidationError("Passwords didn't Matched.")


class KitchenUserProfileForm(forms.ModelForm):
	email = forms.CharField(widget=forms.EmailInput(
		attrs={'class': 'form-control', 'placeholder': 'Email', 'readonly': 'true'}))
	password = forms.CharField(widget=forms.PasswordInput(render_value = True,
		attrs={'class': 'form-control', 'placeholder': 'Password', 'readonly': 'true'}))
	first_name = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'First Name', 'readonly': 'true'}))
	last_name = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Last Name', 'readonly': 'true'}))
	username = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Username', 'readonly': 'true'}))
	phone = forms.CharField(widget=forms.TextInput(
		attrs={'class': 'form-control', 'placeholder': 'Phone No.', 'readonly': 'true', 'maxlength':'10', 'onkeypress':'return onlyNumberKey(event)'}))

	class Meta:
		model = User
		fields = ['username', 'email', 'phone', 'password', 'first_name', 'last_name']

		def save(self, commit=True):
			user = super().save(commit=False)
			user.is_kitchen = True
			if commit:
				user.save()
			return user


class KitchenForm(forms.ModelForm):
	latitude = forms.FloatField(widget=forms.TextInput(
		attrs={'id': 'lat', 'readonly': 'true'}))
	longitude = forms.FloatField(widget=forms.TextInput(
		attrs={'id': 'lon', 'readonly': 'true'}))
	paytmNo = forms.CharField(widget=forms.TextInput(
		attrs={'placeholder': 'PayTm No.', 'maxlength':'10', 'onkeypress':'return onlyNumberKey(event)'}))

	def __init__(self, *args, **kwargs):
		self.user = kwargs.pop('user',None)
		super(KitchenForm, self).__init__(*args, **kwargs)
		if self.user.kit_Created:
			if self.user.kitchens.approved:
				self.fields['kitName'].widget.attrs['readonly'] = True
				self.fields['address'].widget.attrs['readonly'] = True
				self.fields['youTubeReview'].widget.attrs['readonly'] = True
				self.fields['youTubeLink'].widget.attrs['readonly'] = True
				self.fields['city'].widget.attrs['disabled'] = True
				self.fields['city'].required = False
				self.fields['landmark'].widget.attrs['readonly'] = True
				self.fields['postalCode'].widget.attrs['readonly'] = True
				self.fields['floorNo'].widget.attrs['readonly'] = True
				self.fields['video'].widget.attrs['disabled'] = True
				self.fields['fssaiLicNo'].widget.attrs['readonly'] = True
				self.fields['fssaiName'].widget.attrs['readonly'] = True
				self.fields['fssaiAdd'].widget.attrs['readonly'] = True
				self.fields['fssaiExpiry'].widget.attrs['readonly'] = True
				self.fields['fssaiCerti'].widget.attrs['disabled'] = True
				self.fields['kyc'].widget.attrs['disabled'] = True

	def clean_city(self):
		if self.instance and self.instance.pk:
			return self.instance.city
		else:
			return self.cleaned_data['city']

	class Meta:
		model = Kitchens
		fields = ['kitName', 'mode', 'acceptAdvcOrders', 'wantAdvancePayment', 'deliveryTime', 'deliveryCharge', 'deliveryRadius', 'pureVeg', 'paytmLink', 'paytmNo', 'address', 'city', 'landmark', 'postalCode', 'floorNo', 'latitude',
					'longitude', 'dp', 'chefDp', 'video', 'QRCode', 'fssaiLicNo', 'fssaiName', 'fssaiAdd', 'fssaiExpiry', 'fssaiCerti', 'kyc', 'degree', 'youTubeReview', 'youTubeLink']


class CategoryForm(forms.ModelForm):
	class Meta:
		model = Categories
		fields = ['category']


class ItemForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		self.user = kwargs.pop('user',None)
		super(ItemForm, self).__init__(*args, **kwargs)
		self.fields['category'].queryset = Categories.objects.filter(kit=self.user.kitchens.id)

	class Meta:
		model = Items
		fields = ['category', 'itemName', 'itemType', 'price', 'image', 'condition', 'itemDesc']
		widgets={
			'category': forms.Select(attrs={'class':'form-control'}),
			'itemName': forms.TextInput(attrs={'class':'form-control'}),
			'itemType': forms.Select(attrs={'class':'form-control'}),
			'price': forms.TextInput(attrs={'class':'form-control'}),
			'condition': forms.Textarea(attrs={'class':'form-control', 'rows':2}),
			'itemDesc': forms.Textarea(attrs={'class':'form-control', 'rows':2}),
		}


class SubItemForm(forms.ModelForm):
	class Meta:
		model = SubItems
		fields = ['name', 'price', 'item']
		widgets={
			'name': forms.TextInput(attrs={'class':'form-control'}),
			'price': forms.TextInput(attrs={'class':'form-control'}),
		}


class MenuForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		self.user = kwargs.pop('user',None)
		super(MenuForm, self).__init__(*args, **kwargs)
		self.fields['item'].queryset = Items.objects.filter(kit=self.user.kitchens.id)

	class Meta:
		model = Menus
		fields = ['item', 'offer', 'out_of_stock', 'minOrder']
		widgets={
			'item': forms.Select(attrs={'class':'form-control'}),
			'offer': forms.TextInput(attrs={'class':'form-control'}),
			'minOrder': forms.TextInput(attrs={'class':'form-control'}),
		}

kitchen/templates/complaintsAndRefunds.html
{% extends 'baseKit.html' %}
{% load static %}

{% block content %}

<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <h1 class="mb-2 bread">Complaints and Refund Requests</h1>
            </div>
        </div>
    </div>
</section>
<br>
<section class="container-fluid">
    <table class="table table-bordered table-hover">
        <thead class="table-danger">
          <tr>
            <th scope="col">Request ID</th>
            <th scope="col">Order ID</th>
            <th scope="col">Customer's Name</th>
            <th scope="col">Request Date</th>
            <th scope="col">Subject</th>
            <th scope="col">Issue</th>
            <th scope="col">PayTm No</th>
            <th scope="col">Status</th>
            <th scope="col">Comments</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
        {% for var in requests %}
          <tr>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <th scope="row">{{var.id}}</th>
                <th scope="row">{{var.order.id}}</th>
                <td>{{var.user.first_name}} {{var.user.last_name}}</td>
                <td>{{var.request_date}}</td>
                <td>{{var.subject}}</td>
                <td><textarea rows="4" cols="30" readonly>{{ var.issue }}</textarea></td>
                <td>{{var.paytmNo}}</td>
                <td>
                    <select name="status{{var.id}}" id="status{{var.id}}">
                        <option value="Under Process" {% if var.status == "Under Process" %} selected {% endif %}>Under Process
                        </option>
                        <option value="Closed" {% if var.status == "Closed" %} selected {% endif %}>Closed
                        </option>
                    </select>
                    <br><br>
                    {% if var.status == "Closed" %}
                    {{ var.closing_date }}
                    {% endif %}
                </td>
                <td>
                    {% if var.status == "Closed" %}
                    <textarea id="comments{{var.id}}" name="comments{{var.id}}" rows="4" cols="40" readonly>{{ var.comments }}</textarea>
                    {% else %}
                    <textarea id="comments{{var.id}}" name="comments{{var.id}}" rows="4" cols="40" maxlength="200">{{ var.comments }}</textarea>
                    {% endif %}
                </td>
                <td>
                    <input type="hidden" name="requestid" id="requestid" value="{{ var.id }}" />
                    <button type="submit" class="btn {% if var.status == "Under Process" %}btn-success" {% else %}btn-light" disabled{% endif %}>Set Status</button>
                </td>
            </form>
          </tr>
        {% endfor %}
        </tbody>
    </table>
</section>

{% include "notificationModal.html" %}
{% endblock %}

kitchen/templates/kitLogin.html
{% extends 'baseKit.html' %}
{% load static %}

{% block content %}

<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <h1 class="mb-2 bread">Login</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="/">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Login <i class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>


<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">


<div class="container">
    <br>
    <div class="card bg-light">
        <article class="card-body mx-auto" style="max-width: 400px;">
            <h4 class="card-title mt-3 text-center">Login</h4>
            {% if error_message %}
            <div class="col-sm-offset-2 col-sm-12">
                <span class="text-danger large">{{ error_message }}</span>
            </div>
            {% endif %}
            <br>
            <form role="form" action="#" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                    </div>
                    <input name="username" class="form-control" placeholder="Username" type="text">
                </div>
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    <input name="password" class="form-control" placeholder="Password" type="password">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Submit</button>
                </div>
                <p class="text-center">Don't have an account? <a href="{% url 'kitchenRegistration' %}">Register</a> </p>
            </form>
        </article>
    </div> <!-- card.// -->
</div>
<!--container end.//-->

<br><br>

<style>
    .divider-text {
    position: relative;
    text-align: center;
    margin-top: 15px;
    margin-bottom: 15px;
}
.divider-text span {
    padding: 7px;
    font-size: 12px;
    position: relative;
    z-index: 2;
}
.divider-text:after {
    content: "";
    position: absolute;
    width: 100%;
    border-bottom: 1px solid #ddd;
    top: 55%;
    left: 0;
    z-index: 1;
}
</style>

{% endblock %}

kitchen/templates/kitUserProfile.html
{% extends 'baseKit.html' %}
{% load static %}

{% block content %}

<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <h1 class="mb-2 bread">Register</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="/">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Register <i class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>


<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">


<div class="container">
    <br>
    <div class="card bg-light" id="profile">
        <article class="card-body mx-auto" style="max-width: 400px;">
            <h4 class="card-title mt-3 text-center">Edit Your Profile</h4>
            <br>
            {% if error_message %}
            <div class="col-sm-offset-2 col-sm-12">
                <span class="text-danger large">{{ error_message }}</span>
            </div>
            {% endif %}
            {% if form.non_field_errors %}
                <div class="col-sm-offset-2 col-sm-12">
                    <span class="text-danger large">{{ form.non_field_errors }}</span>
                </div>
            {% endif %}
            <br>
            <form method="post" role="form" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group input-group" id="username">
                    <div class="col-sm-offset-2 col-sm-12">
                        <span class="text-danger small">{{ form.username.errors }}</span>
                    </div>
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                    </div>
                    {{form.username}}
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="edit-username"><a style='cursor: pointer; color: rgb(63, 153, 238);' title="Edit" class="edit-username"><i class="fa fa-edit"></i></a></span>
                    </div>
                </div>
                <hr>
                <div class="form-group input-group" id="fname">
                    <div class="col-sm-offset-2 col-sm-12">
                        <span class="text-danger small">{{ form.first_name.errors }}</span>
                    </div>
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                    </div>
                    {{form.first_name}}
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="edit-fname"><a style='cursor: pointer; color: rgb(63, 153, 238);' title="Edit" class="edit-fname"><i class="fa fa-edit"></i></a></span>
                    </div>
                </div>
                <hr>
                <div class="form-group input-group" id="lname">
                    <div class="col-sm-offset-2 col-sm-12">
                        <span class="text-danger small">{{ form.last_name.errors }}</span>
                    </div>
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                    </div>
                    {{form.last_name}}
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="edit-lname"><a style='cursor: pointer; color: rgb(63, 153, 238);' title="Edit" class="edit-lname"><i class="fa fa-edit"></i></a></span>
                    </div>
                </div>
                <hr>
                <div class="form-group input-group" id="email">
                    <div class="col-sm-offset-2 col-sm-12">
                        <span class="text-danger small">{{ form.email.errors }}</span>
                    </div>
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                    </div>
                    {{form.email}}
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="edit-email"><a style='cursor: pointer; color: rgb(63, 153, 238);' title="Edit" class="edit-email"><i class="fa fa-edit"></i></a></span>
                    </div>
                </div>
                <hr>
                <div class="form-group input-group" id="phone">
                    <div class="col-sm-offset-2 col-sm-12">
                        <span class="text-danger small">{{ form.phone.errors }}</span>
                    </div>
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-phone"></i> </span>
                    </div>
                    {{form.phone}}
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="edit-phone"><a style='cursor: pointer; color: rgb(63, 153, 238);' title="Edit" class="edit-phone"><i class="fa fa-edit"></i></a></span>
                    </div>
                    <div class="form-group input-group" id="phoneotp">
                    </div>
                </div>
                <hr>
                <div class="form-group input-group" id="pass">
                    <div class="col-sm-offset-2 col-sm-12">
                        <span class="text-danger small">{{ form.password.errors }}</span>
                    </div>
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    {{form.password}}
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="edit-pass"><a style='cursor: pointer; color: rgb(63, 153, 238);' title="Edit" class="edit-pass"><i class="fa fa-edit"></i></a></span>
                    </div>
                    <div class="form-group input-group" id="rpass">
                    </div>
                </div>
            </form>
        </article>
    </div>
</div>
<script>

    $(document).on("click", ".edit-username", function (event) {
      $("#fname").load(" #fname > *");
      $("#lname").load(" #lname > *");
      $("#email").load(" #email > *");
      $("#phone").load(" #phone > *");
      $("#pass").load(" #pass > *");
      document.getElementById('id_username').readOnly = false;
      $("#edit-username").html('');
      $("#edit-username").append("<button type='submit' value='username' name='submit' class='btn'> <i class='fa fa-check' style='color: green;' ></i> </button>");
    });

    $(document).on("click", ".edit-fname", function (event) {
      $("#username").load(" #username > *");
      $("#lname").load(" #lname > *");
      $("#email").load(" #email > *");
      $("#phone").load(" #phone > *");
      $("#pass").load(" #pass > *");
      document.getElementById('id_first_name').readOnly = false;
      $("#edit-fname").html('');
      $("#edit-fname").append("<button type='submit' value='fname' name='submit' class='btn'> <i class='fa fa-check' style='color: green;' ></i> </button>");
    });

    $(document).on("click", ".edit-lname", function (event) {
      $("#fname").load(" #fname > *");
      $("#username").load(" #username > *");
      $("#email").load(" #email > *");
      $("#phone").load(" #phone > *");
      $("#pass").load(" #pass > *");
      document.getElementById('id_last_name').readOnly = false;
      $("#edit-lname").html('');
      $("#edit-lname").append("<button type='submit' value='lname' name='submit' class='btn'> <i class='fa fa-check' style='color: green;' ></i> </button>");
    });

    $(document).on("click", ".edit-email", function (event) {
      $("#fname").load(" #fname > *");
      $("#lname").load(" #lname > *");
      $("#username").load(" #username > *");
      $("#phone").load(" #phone > *");
      $("#pass").load(" #pass > *");
      document.getElementById('id_email').readOnly = false;
      $("#edit-email").html('');
      $("#edit-email").append("<button type='submit' value='email' name='submit' class='btn'> <i class='fa fa-check' style='color: green;' ></i> </button>");
    });

    $(document).on("click", ".edit-phone", function (event) {
      $("#fname").load(" #fname > *");
      $("#lname").load(" #lname > *");
      $("#email").load(" #email > *");
      $("#username").load(" #username > *");
      $("#pass").load(" #pass > *");
      document.getElementById('id_phone').readOnly = false;
      $("#edit-phone").html('');
      $("#edit-phone").append("<button type='button' class='verify-phone btn'>Send OTP</button>");
    });

    $(document).on("click", ".verify-phone", function (event) {
      $("#fname").load(" #fname > *");
      $("#lname").load(" #lname > *");
      $("#email").load(" #email > *");
      $("#username").load(" #username > *");
      $("#pass").load(" #pass > *");
      document.getElementById('id_phone').readOnly = true;
      $("#edit-phone").html('');
      $("#edit-phone").append("<button type='submit' value='phone' name='submit' class='btn'> <i class='fa fa-check' style='color: green;' ></i> </button>");
      $("#phoneotp").html('');
      $("#phoneotp").append("<input type='text' name='otp' class='form-control' placeholder='Enter OTP' required id='otp'>");
    });

    $(document).on("click", ".edit-pass", function (event) {
      $("#fname").load(" #fname > *");
      $("#lname").load(" #lname > *");
      $("#email").load(" #email > *");
      $("#phone").load(" #phone > *");
      $("#username").load(" #username > *");
      document.getElementById('id_password').readOnly = false;
      document.getElementById('id_password').value = "";
      $("#edit-pass").html('');
      $("#edit-pass").append("<button type='submit' value='pass' name='submit' class='btn'> <i class='fa fa-check' style='color: green;' ></i> </button>");
      $("#rpass").html('');
      $("#rpass").append("<div class='input-group-prepend'><span class='input-group-text'> <i class='fa fa-lock'></i> </span></div><input type='password' name='rpassword' class='form-control' placeholder='Re-enter Password' required id='id_rpassword'>");
    });
    
</script>


<br><br>

<style>
    .divider-text {
    position: relative;
    text-align: center;
    margin-top: 15px;
    margin-bottom: 15px;
}
.divider-text span {
    padding: 7px;
    font-size: 12px;
    position: relative;
    z-index: 2;
}
.divider-text:after {
    content: "";
    position: absolute;
    width: 100%;
    border-bottom: 1px solid #ddd;
    top: 55%;
    left: 0;
    z-index: 1;
}
</style>

{% endblock %}

kitchen/templates/menuFormModal.html
    {% if error_message %}
    <div class="col-sm-offset-2 col-sm-12">
        <span class="text-danger large">{{ error_message }}</span>
    </div>
    {% endif %}
    {% for item in menuform.forms %}
    {{ menuform.management_form }}
    {% csrf_token %}
    <tr>
        {% for field in item %}
        <div class="col-sm-offset-2 col-sm-12">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <td>{{ field}}</td>
        {% endfor %}
        <!-- <td><input type="number" value="" name="offer{{ item.id }}" /></td>
        <td><input type="number" value="" name="minOrder{{ item.id }}" /></td>
        <td><input type="checkbox" checked data-toggle="toggle" data-on="Available"
                data-off="Unavailable" data-onstyle="success" data-offstyle="danger"
                name="radio{{ item.id }}" /></td>
        <td><input type="checkbox" class="form-check-input" name="tick{{ item.id }}" /></td> -->
    </tr>
    {% endfor %}

kitchen/templates/subItemsModal.html
    
    {% if error_message %}
    <div class="col-sm-offset-2 col-sm-12">
        <span class="text-danger large">{{ error_message }}</span>
    </div>
    {% endif %}
    {% if subItems %}
    {% for form in subItems.forms %}
    {{ subItems.management_form }}
    {% csrf_token %}
    <tr>
        {% for field in form %}
        <td>{{ field }}</td>
        {% endfor %}
    </tr>
    {% endfor %}
    {% endif %}